[global_tags]

host_ip = ""

deployment = ""
projectid = ""

[agent]
interval = "60s"
round_interval = true
metric_batch_size = 1000
metric_buffer_limit = 10000
collection_jitter = "0s"
flush_interval = "60s"
flush_jitter = "0s"
precision = "0s"
logtarget = "file"
logfile = "/logs/telegraf.log"
logfile_rotation_max_size = "10MB"
logfile_rotation_max_archives = 10
debug = false
quiet = false
hostname = "cscocoplivein01"
omit_hostname = false

[[inputs.cpu]]
interval = "120s"
percpu = false
totalcpu = true
collect_cpu_time = true
report_active = true
core_tags = false
tags = {category = "host_os_metrics"}

[[inputs.mem]]
interval = "120s"
tags = {category = "host_os_metrics"}

[[inputs.disk]]
interval = "120s"
tags = {category = "host_os_metrics"}
#mount_points = ["/"]
ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs", "/dev/loop0", "/dev/loop1", "/dev/loop2", "/dev/loop3", "/dev/loop4", "/dev/loop5", "/dev/loop*"]


[[inputs.net]]
interval = "120s"
tags = {category = "host_os_metrics"}
interfaces = ["ens*", "eth*"]


[[processors.rename]]

  [[processors.rename.replace]]
    tag = "com.docker.compose.project"
    dest = "docker_compose_project"
  [processors.rename.replace.tagpass]
  category = ["docker_metrics"]

  [[processors.rename.replace]]
    tag = "com.docker.compose.project.config_files"
    dest = "docker_compose_file"
  [processors.rename.replace.tagpass]
  category = ["docker_metrics"]

  [[processors.rename.replace]]
    tag = "com.docker.compose.service"
    dest = "docker_service_name"
  [processors.rename.replace.tagpass]
  category = ["docker_metrics"]

  [[processors.rename.replace]]
    tag = "com.docker.compose.version"
    dest = "docker_compose_version"
  [processors.rename.replace.tagpass]
  category = ["docker_metrics"]

  [[processors.rename.replace]]
    field = "buffer_pools_mapped - 'non-volatile memory'_total_capacity_in_bytes"
    dest = "buffer_pools_mapped_non_volatile_memory_total_capacity_in_bytes"
  [processors.rename.replace.tagpass]
  category = ["opensearch_metrics"]

  [[processors.rename.replace]]
    field = "buffer_pools_mapped - 'non-volatile memory'_count"
    dest = "buffer_pools_mapped_non_volatile_memory_count"
  [processors.rename.replace.tagpass]
  category = ["opensearch_metrics"]

  [[processors.rename.replace]]
    field = "buffer_pools_mapped - 'non-volatile memory'_used_in_bytes"
    dest = "buffer_pools_mapped_non_volatile_memory_used_in_bytes"
  [processors.rename.replace.tagpass]
  category = ["opensearch_metrics"]

[[outputs.discard]]
[outputs.discard.tagpass]
category = ["host_os_metrics", "docker_metrics", "opensearch_metrics"]
