[[inputs.rda_ping]]
enabled = true
tags = { kpi_metric = "yes" }
alias = "cfx_ping"
input_definition = '''

collector:
  ## Input Pstream to collect the ICMP Ping Metrics for selected Network Devices
  input_criteria:
    frequency: 60
    pstream: "network_access_verification"
    query: "auth_state = 'Success'"

  ## ICMP Ping Metrics Colelction Properties
  ping_properties:
    - name: default
      count: 3
      timeout: 5.0
      interval: 1.0
      size: 56
      frequency: 30
      ipv4: true

  transformations: ["enrich_device_info"]
  output_stream: 
    name: rda_icmp_ping_metrics
    type: pstream

  ## Data transformations for Enrichment
  data_transformations:
    - name: "enrich_device_info"
      type: enrich
      dataset: "network_device_chassis_dict"
      source_key_columns: ["target_ip"]
      dict_key_columns: ["target_ip"]
      enrich_columns: ["hostname","product_id","vendor"]
      enrich_columns_as: ["device_hostname","device_model","device_vendor"]
      return_empty_columns: "yes"
      enrich_column_defaults: ["Not Available","Not Available","Not Available"]
'''
