[[inputs.rda_cert]]
  enabled = true
  alias = "ssl_certificate"
  input_definition = '''
  collector:

    ## Input Pstream to collect the SSL Certificate Metrics for selected URLs
    input_criteria:
      frequency: 180
      pstream: "discovery"
      query: "type = 'ssl_metrics' and url_field is not empty"
      url_field: "url_field"
      

    ## SSL Certificate Metrics Colelction Properties
    cert_properties:
      - name: default
        timeout: 5
        frequency: 300

    output_stream:
      name: "rda_ssl_certificate_metrics"
      type: "pstream"

    ## Data Transformation for Enrichment
    data_transformations:
      - name: classify_expiry
        type: starlark
        script: |
          def apply(metric):
            expiry_days = metric.fields.get("expiry_days", None)
            if expiry_days != None:
              if expiry_days < 0:
                metric.fields["expiry_status"] = "expired"
              elif expiry_days < 30:
                metric.fields["expiry_status"] = "critical"
              elif expiry_days < 90:
                 metric.fields["expiry_status"] = "warning"
              else:
                 metric.fields["expiry_status"] = "healthy"
            return metric
  '''
