[[inputs.rda_snmp_trap]]
enabled = true
tags = { input = "snmp_trap" }

input_definition = '''
collector:
  snmp_trap_properties:
    bind_host: "0.0.0.0"
    port: 162
    template_path: "/event_gw_config/snmptrap/trap_template.json"
    worker_count: 8
    queue_size: 200
    flush_interval: 1
    batch_size: 8000
    timeout: 60

  output_stream:
    name: "snmp_trap_events_stream"
    type: "pstream"

  data_transformations:
    - name: network_inventory_enrich
      type: enrich
      dataset: "network_device_chassis_dict"
      dict_key_columns: ["target_ip"]
      source_key_columns: ["rda_gw_client_ip"]
      enrich_columns: ["device_status", "hostname", "vendor", "product_id"]
      enrich_columns_as: ["device_status", "device_hostname", "device_vendor", "device_model"]
      return_empty_columns: true
      enrich_column_defaults: ["UNMANAGED", "Not Available", "Not Available", "Not Available"]
'''
